measure_name: IMA
description: Prostate Cancer Screening (HEDIS/Cotiviti)
rules:
  age_range:
  - 66
  - 100
  age_as_of: December 31
  anchor_date_type: calendar_end
  continuous_enrollment:
    period_months: 12
    allowable_gap_days: 45
    no_gap_on_last_day: true
  initial_population:
  - event: Medicare Product Line
    criteria: Product Line = Medicare
    table: PSA_ENROLLMENT_IN
  - event: Outpatient Visit
    value_set_names:
    - Outpatient
    table: PSA_VISIT_IN
  exclusions:
  - name: Hospice
    value_set_names:
    - Hospice Encounter
    - Hospice Intervention
  - name: Prostate Cancer
    value_set_names:
    - Prostate Cancer and History of Prostate Cancer
  - name: Death
    criteria: Date of death within measurement period
  clinical_events:
    numerator_components:
    - name: PSA Test
      value_set_names:
      - PSA Lab Test
      table: PSA_LAB_IN
