measure_name: IMA
description: Immunizations for Adolescents
rules:
  age_range: [13, 13] # Usually 13th birthday
  age_as_of: "December 31"
  anchor_date_type: "calendar_end"
  
  continuous_enrollment:
    period_months: 12
    allowable_gap_days: 45
    no_gap_on_last_day: true

  initial_population:
    - event: "Outpatient Visit"
      value_set_names: ["Outpatient"]
      table: "visit"

  exclusions:
    - name: "Hospice"
      value_set_names: ["Hospice Encounter", "Hospice Intervention"]
    - name: "Death"
      criteria: "Date of death within measurement period"

  clinical_events:
    numerator_components:
      - name: "Meningococcal"
        value_set_names: ["Meningococcal Vaccine", "Meningococcal Allergen"]
        table: "visit"
      - name: "Tdap"
        value_set_names: ["Tdap Vaccine", "Tdap Allergen"]
        table: "visit"
      - name: "HPV"
        value_set_names: ["HPV Vaccine", "HPV Allergen"]
        table: "visit"
