measure_name: Universal
description: Generic HEDIS measure for universal processing
rules:
  age_range: [0, 100]
  age_as_of: "December 31"
  anchor_date_type: "calendar_end"
  
  continuous_enrollment:
    period_months: 12
    allowable_gap_days: 45
    no_gap_on_last_day: true

  initial_population:
    - event: "Outpatient Visit"
      value_set_names: ["Outpatient"]
      table: "visit"

  exclusions:
    - name: "Hospice"
      value_set_names: ["Hospice Encounter", "Hospice Intervention"]

  clinical_events:
    numerator_components: [] # Will be populated dynamically from Excel
